rules = [
  DisableSyntax
  LeakingImplicitClassVal
  NoValInForComprehension
  ProcedureSyntax
]

DisableSyntax.noFinalize = true
DisableSyntax.noImplicitObject = true
DisableSyntax.noTabs = true
DisableSyntax.noReturns = true

DisableSyntax.regex = [
  {
    id = println
    pattern = "\\bprintln\\b"
    message = "Use a logger instead of println"
  }
]
