version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: TASK_DEFININION_ARN
        LoadBalancerInfo:
          ContainerName: "KoskiContainer"
          ContainerPort: 8080
        PlatformVersion: "1.4.0"
