version: "3"
services:

  postgres:
    image: "postgres:12.11@sha256:15017a063c249afe1a87f6c6b163eddc3205601040b22c0f8b10625ae6c75402"
    command: "postgres -c max_connections=200 -c log_statement=all -c log_destination=stderr"
    environment:
    - "POSTGRES_USER=oph"
    - "POSTGRES_PASSWORD=oph"
    - "TZ=Europe/Helsinki"
    ports:
    - "5432:5432"
    volumes:
    - "./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  opensearch:
    build: "./opensearch"
    environment:
    - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
    - "discovery.type=single-node"
    - "plugins.security.disabled=true"
    ports:
    - "9200:9200"
    volumes:
    - "./opensearch/opensearch-docker.yml:/usr/share/opensearch/config/opensearch.yml:ro"

  dynamodb:
    image: "amazon/dynamodb-local@sha256:f02384481c5133136cfd7edc82c6aed431e85a27bf5886fd637b889bdc0af6d5"
    ports:
    - "8000:8000"
