version: "3"
services:

  postgres:
    image: "postgres:15.17@sha256:f30e3de0ac9cc938dac627ef2231099867c694b5f949fadb924c8c977428c399"
    command: "postgres -c max_connections=200 -c log_statement=all -c log_destination=stderr"
    environment:
      - "POSTGRES_USER=oph"
      - "POSTGRES_PASSWORD=oph"
      - "TZ=Europe/Helsinki"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  opensearch:
    build: "./opensearch"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    ports:
      - "9200:9200"
    volumes:
      - "./opensearch/opensearch-docker.yml:/usr/share/opensearch/config/opensearch.yml"

  dynamodb:
    image: "amazon/dynamodb-local:2.6.1@sha256:1856c05cc66a0e49dc1099e483ad2851477eeebe2135250ac11a1d1227db54b1"
    ports:
      - "8000:8000"

  localstack:
    container_name: koski-localstack
    image: localstack/localstack:s3-latest@sha256:2c32486ed9ce66afbc6f8792dc6719a35890b454ecae7dc09eb9acecd057eda8
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
