version: "3"
services:

  postgres:
    command: postgres -c 'max_connections=200'
    image: "postgres:12.3"
    environment:
    - "POSTGRES_DB=koski"
    - "POSTGRES_USER=oph"
    - "POSTGRES_PASSWORD=oph"
    ports:
    - "5432:5432"
    volumes:
    - "./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  elasticsearch:
    build: "./elasticsearch"
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
    - "9200:9200"
    volumes:
    - "./elasticsearch/elasticsearch-docker.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
    - "8000:8000"
