version: "3"
services:

  postgres:
    image: "postgres:15.2@sha256:78a275d4c891f7b3a33d3f1a78eda9f1d744954d9e20122bfdc97cdda25cddaf"
    command: "postgres -c max_connections=200 -c log_statement=all -c log_destination=stderr"
    environment:
      - "POSTGRES_USER=oph"
      - "POSTGRES_PASSWORD=oph"
      - "TZ=Europe/Helsinki"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  opensearch:
    build: "./opensearch"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    ports:
      - "9200:9200"
    volumes:
      - "./opensearch/opensearch-docker.yml:/usr/share/opensearch/config/opensearch.yml"

  dynamodb:
    image: "amazon/dynamodb-local:2.5.2@sha256:d7ebddeb60fa418bcda218a6c6a402a58441b2a20d54c9cb1d85fd5194341753"
    ports:
      - "8000:8000"

  localstack:
    container_name: koski-localstack
    image: localstack/localstack:3.7.2@sha256:811d4cd67e6cc833cd5849ddaac454abd90c0d0fc00d402f8f82ee47926c5e10
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
