import { Koodistokoodiviite } from './Koodistokoodiviite'
import { LocalizedString } from './LocalizedString'
import { LaajuusOpintopisteissä } from './LaajuusOpintopisteissa'

/**
 * Valtakunnallisen lukion/IB-lukion moduulin tunnistetiedot
 *
 * @see `fi.oph.koski.schema.LukionÄidinkielenModuuli2019`
 */
export type LukionÄidinkielenModuuli2019 = {
  $class: 'fi.oph.koski.schema.LukionÄidinkielenModuuli2019'
  tunniste: Koodistokoodiviite<
    'moduulikoodistolops2021',
    | 'ÄI1'
    | 'ÄI2'
    | 'ÄI3'
    | 'ÄI4'
    | 'ÄI5'
    | 'ÄI6'
    | 'ÄI7'
    | 'ÄI8'
    | 'ÄI9'
    | 'ÄI10'
    | 'ÄI11'
    | 'MO1'
    | 'MO2'
    | 'MO3'
    | 'MO4'
    | 'MO5'
    | 'MO6'
    | 'MO7'
    | 'MO8'
    | 'MO9'
    | 'MO10'
    | 'MO11'
    | 'ÄIS1'
    | 'ÄIS2'
    | 'ÄIS3'
    | 'ÄIS4'
    | 'ÄIS5'
    | 'ÄIS6'
    | 'ÄIS7'
    | 'ÄIS8'
    | 'ÄIS9'
    | 'ÄIS10'
    | 'ÄIS11'
    | 'ÄIR1'
    | 'ÄIR2'
    | 'ÄIR3'
    | 'ÄIR4'
    | 'ÄIR5'
    | 'ÄIR6'
    | 'ÄIR7'
    | 'ÄIR8'
    | 'ÄIR9'
    | 'ÄIR10'
    | 'ÄIR11'
    | 'ÄIV1'
    | 'ÄIV2'
    | 'ÄIV3'
    | 'ÄIV4'
    | 'ÄIV5'
    | 'ÄIV6'
    | 'ÄIV7'
    | 'ÄIV8'
    | 'ÄIV9'
    | 'ÄIV10'
    | 'ÄIV11'
    | 'S21'
    | 'S22'
    | 'S23'
    | 'S24'
    | 'S25'
    | 'S26'
    | 'S27'
    | 'S28'
    | 'S29'
    | 'S210'
    | 'S211'
    | 'SV21'
    | 'SV22'
    | 'SV23'
    | 'SV24'
    | 'SV25'
    | 'SV26'
    | 'SV27'
    | 'SV28'
    | 'SV29'
    | 'SV210'
    | 'SV211'
  >
  laajuus: LaajuusOpintopisteissä
  pakollinen: boolean
}

export const LukionÄidinkielenModuuli2019 = (o: {
  tunniste: Koodistokoodiviite<
    'moduulikoodistolops2021',
    | 'ÄI1'
    | 'ÄI2'
    | 'ÄI3'
    | 'ÄI4'
    | 'ÄI5'
    | 'ÄI6'
    | 'ÄI7'
    | 'ÄI8'
    | 'ÄI9'
    | 'ÄI10'
    | 'ÄI11'
    | 'MO1'
    | 'MO2'
    | 'MO3'
    | 'MO4'
    | 'MO5'
    | 'MO6'
    | 'MO7'
    | 'MO8'
    | 'MO9'
    | 'MO10'
    | 'MO11'
    | 'ÄIS1'
    | 'ÄIS2'
    | 'ÄIS3'
    | 'ÄIS4'
    | 'ÄIS5'
    | 'ÄIS6'
    | 'ÄIS7'
    | 'ÄIS8'
    | 'ÄIS9'
    | 'ÄIS10'
    | 'ÄIS11'
    | 'ÄIR1'
    | 'ÄIR2'
    | 'ÄIR3'
    | 'ÄIR4'
    | 'ÄIR5'
    | 'ÄIR6'
    | 'ÄIR7'
    | 'ÄIR8'
    | 'ÄIR9'
    | 'ÄIR10'
    | 'ÄIR11'
    | 'ÄIV1'
    | 'ÄIV2'
    | 'ÄIV3'
    | 'ÄIV4'
    | 'ÄIV5'
    | 'ÄIV6'
    | 'ÄIV7'
    | 'ÄIV8'
    | 'ÄIV9'
    | 'ÄIV10'
    | 'ÄIV11'
    | 'S21'
    | 'S22'
    | 'S23'
    | 'S24'
    | 'S25'
    | 'S26'
    | 'S27'
    | 'S28'
    | 'S29'
    | 'S210'
    | 'S211'
    | 'SV21'
    | 'SV22'
    | 'SV23'
    | 'SV24'
    | 'SV25'
    | 'SV26'
    | 'SV27'
    | 'SV28'
    | 'SV29'
    | 'SV210'
    | 'SV211'
  >
  laajuus: LaajuusOpintopisteissä
  pakollinen: boolean
}): LukionÄidinkielenModuuli2019 => ({
  $class: 'fi.oph.koski.schema.LukionÄidinkielenModuuli2019',
  ...o
})

LukionÄidinkielenModuuli2019.className =
  'fi.oph.koski.schema.LukionÄidinkielenModuuli2019' as const

export const isLukionÄidinkielenModuuli2019 = (
  a: any
): a is LukionÄidinkielenModuuli2019 =>
  a?.$class === 'fi.oph.koski.schema.LukionÄidinkielenModuuli2019'
