runs:
  using: composite
  steps:
    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        architecture: "x64"
        distribution: "zulu"
        cache: "maven"
