inputs:
  shardIndex:
    required: true
    type: string
  shardTotal:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Run frontend tests
      env:
        MOCHA_SHARD_INDEX: ${{inputs.shardIndex}}
        MOCHA_SHARD_TOTAL: ${{inputs.shardTotal}}
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 45
        command: mvn test -Pmocharunner -Dsuites="fi.oph.koski.mocha.KoskiParallelMochaSpec" -DargLine="-Xms1536m -Xmx1536m" --batch-mode

    - name: Archive test screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: web/target/screenshots
