inputs:
  shardIndex:
    required: true
    type: string
  shardTotal:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup Java"
      uses: ./.github/actions/setup_java_11
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Install js deps
      env:
        PNPM_FROZEN_FLAG: ${{ github.event_name == 'pull_request' && (github.event.pull_request.user.login == 'snyk-io[bot]' || github.event.pull_request.user.login == 'snyk-io') && '--no-frozen-lockfile' || '--frozen-lockfile' }}
      run: cd web && pnpm install $PNPM_FROZEN_FLAG
      shell: bash

    - name: Run frontend tests
      env:
        MOCHA_SHARD_INDEX: ${{inputs.shardIndex}}
        MOCHA_SHARD_TOTAL: ${{inputs.shardTotal}}
      run: mvn scalatest:test -Dsuites="fi.oph.koski.mocha.KoskiParallelMochaSpec" --batch-mode
      shell: bash

    - name: Archive test screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: web/target/screenshots
