inputs:
  index:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Run frontend tests
      run: mvn test -Pmocharunner -Dsuites="fi.oph.koski.mocha.KoskiMochaSpecRunner${{ inputs.index }}"
      shell: bash

    - name: Archive test screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: web/target/screenshots
    - name: show working directory
      run: pwd
      shell: bash
    - name: list current dir content
      run: ls -la
      shell: bash
    - name: list web directory
      run: ls -la web
      shell: bash
    - name: list target directory
      run: ls -la web/target
      shell: bash
    - name: list screenshot directory
      run: ls -la web/target/screenshots
      shell: bash
