name: "Run Koski backend tests"

inputs:
  suites:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Run backend tests
      run: mvn test -DwildcardSuites="${{ inputs.suites }}"
      shell: bash
