package fi.oph.common.koskiuser

trait KoskiSessionStatus

case object SessionStatusExpiredKansalainen extends KoskiSessionStatus
case object SessionStatusExpiredVirkailija extends KoskiSessionStatus
case object SessionStatusNoSession extends KoskiSessionStatus
