packages:
  - .

saveExact: true
engineStrict: true
strictPeerDependencies: true
updateNotifier: false
managePackageManagerVersions: true
minimumReleaseAge: 4320
ignoreScripts: true
minimumReleaseAgeExclude:
  # Renovate security update: jquery@3.5.0
  - jquery@3.5.0
