export default {
  'Koski': 'Koski',
  'Kaikki muutokset tallennettu.': 'Kaikki muutokset tallennettu.',
  'Opintopolku.fi': 'Opintopolku.fi',
  'Kirjaudu ulos': 'Kirjaudu ulos',
  'Aloituspäivä': 'Aloituspäivä',
  'Yritä uudestaan': 'Yritä uudestaan',
  'Tiedoillasi ei löydy opiskeluoikeuksia': 'Tiedoillasi ei löydy opiskeluoikeuksia',
  'Ladataan...': 'Ladataan...',
  'henkilötunnus, nimi tai oppijanumero': 'henkilötunnus, nimi tai oppijanumero',
  'Ei hakutuloksia': 'Ei hakutuloksia',
  'hae': 'hae',
  'Opiskeluoikeuden tyyppi': 'Opiskeluoikeuden tyyppi',
  'Koulutus': 'Koulutus',
  'Tutkinto / osaamisala / nimike': 'Tutkinto / osaamisala / nimike',
  'Tila': 'Tila',
  'Oppilaitos / toimipiste': 'Oppilaitos / toimipiste',
  'Aloitus pvm': 'Aloitus pvm',
  'Luokka / ryhmä': 'Luokka / ryhmä',
  'Opiskelijat': 'Opiskelijat',
  'lakkautettu': 'lakkautettu',
  'Uuden opiskelijan lisäys': 'Uuden opiskelijan lisäys',
  'versiohistoria': 'versiohistoria',
  'Opiskeluoikeuden tilan lisäys': 'Opiskeluoikeuden tilan lisäys',
  'Päivämäärä': 'Päivämäärä',
  'Tila': 'Tila',
  'näyttötutkintomestari': 'näyttötutkintomestari',
  'lisää uusi': 'lisää uusi',
  'Ei siirretä seuraavalle luokalle': 'Ei siirretä seuraavalle luokalle',
  'Siirretään seuraavalle luokalle': 'Siirretään seuraavalle luokalle',
  'kyllä': 'kyllä',
  'ei': 'ei',
  'Ei valintaa': 'Ei valintaa',
  'Perusteen diaarinumero': 'Perusteen diaarinumero',
  httpStatus: {
    400: 'Järjestelmässä tapahtui odottamaton virhe. Yritä myöhemmin uudelleen.',
    404: 'Etsimääsi sivua ei löytynyt',
    409: 'Muutoksia ei voida tallentaa, koska toinen käyttäjä on muuttanut tietoja sivun latauksen jälkeen. Lataa sivu uudelleen.',
    500: 'Järjestelmässä tapahtui odottamaton virhe. Yritä myöhemmin uudelleen.',
    503: 'Palvelimeen ei saatu yhteyttä. Yritä myöhemmin uudelleen.'
  },
  'Pulssi': 'Pulssi',
  'Opiskeluoikeuksien määrä': 'Opiskeluoikeuksien määrä',
  'Kattavuus': 'Kattavuus',
  'Suoritettujen koulutusten määrä': 'Suoritettujen koulutusten määrä',
  'Saavutettavuus': 'Saavutettavuus',
  'saatavilla viimeisen 30 päivän aikana': 'Kuinka suuren osan ajasta palvelu on ollut saatavilla viimeisen 30 päivän aikana',
  'Operaatiot / kk': 'Operaatiot / kk',
  'Peruuta': 'Peruuta',
  'Tallenna': 'Tallenna',
  'Tiedonsiirrot': 'Tiedonsiirrot',
  'Viimeisimmät KOSKI-palveluun siirtyneet opiskelijatiedot': 'Viimeisimmät KOSKI-palveluun siirtyneet opiskelijatiedot',
  'oppilaitoksessa': 'oppilaitoksessa',
  'Yhteenveto siirretyistä oppilaitoksittain': 'Yhteenveto KOSKI-palveluun siirretyistä opiskelijatiedoista oppilaitoksittain.',
  'Siirrettyjen lukumäärä': 'Siirrettyjen lukumäärä',
  'Virheellisten lukumäärä': 'Virheellisten lukumäärä',
  'Opiskelu-oikeuksien lukumäärä': 'Opiskelu-oikeuksien lukumäärä',
  'Lähdejärjestelmä': 'Lähdejärjestelmä',
  'Käyttäjä': 'Käyttäjä',
  'Alla olevien opiskelijoiden tiedot ovat virhetilassa': 'Alla olevien opiskelijoiden tiedot ovat virhetilassa',
  'Opiskelija poistuu virhelistalta': 'Opiskelija poistuu virhelistalta kun virheen aiheuttanut tieto on korjattu lähdejärjestelmässä ja opiskelijan tiedot on siirretty uudelleen onnistuneesti KOSKI-palveluun.',
  'Tiedonsiirtovirheet': 'Tiedonsiirtovirheet',
  'Oppilaitos': 'Oppilaitos',
  'Viimeisin siirto': 'Viimeisin siirto',
  'Aika': 'Aika',
  'Henkilötunnus': 'Henkilötunnus',
  'Nimi': 'Nimi',
  'Virhe': 'Virhe',
  'Tiedot': 'Tiedot',
  'virhe': 'virhe',
  'tiedot': 'tiedot',
  'Sulje': 'Sulje',
  'kaikki': 'kaikki',
  'kuluva vuosi': 'kuluva vuosi',
  'edellinen vuosi': 'edellinen vuosi',
  'Hae tai lisää opiskelija': 'Hae tai lisää opiskelija',
  'Lisää uusi opiskelija': 'Lisää uusi opiskelija',
  'Tunnus': 'Tunnus', // login page
  'Salasana': 'Salasana', // login page
  'Kirjaudu sisään': 'Kirjaudu sisään', // login page
  'Login - Koski - Opintopolku.fi': 'Login - Koski - Opintopolku.fi' // login page
}