runs:
  using: composite
  steps:
    - name: Set up Java 11 and 23
      uses: actions/setup-java@v4
      with:
        architecture: "x64"
        distribution: "zulu"
        cache: "maven"
        java-version: |
          23
          11
