runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup_pnpm_cache
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "24.14.0"

    - name: Configure sysctl limits for OpenSearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      shell: bash

    - name: Start Postgres and OS containers
      run: docker compose --progress quiet up -d
      shell: bash

    - name: Restore target dir
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: "target/"
        key: ${{ runner.os }}-target-${{ github.sha }}
        fail-on-cache-miss: "true"
