runs:
  using: composite
  steps:
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: "8"
        architecture: x64

    - name: Setup Node 14
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Configure sysctl limits for Elasticsearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      shell: bash

    - name: Start Postgres and ES containers
      run: docker-compose up -d
      shell: bash
