runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup_pnpm_cache
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "22.14.0"

    - name: Configure sysctl limits for OpenSearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      shell: bash

    - name: Start Postgres and OS containers
      run: docker compose --progress quiet up -d
      shell: bash

    - name: Restore target dir
      uses: actions/cache/restore@v4
      with:
        path: "target/"
        key: ${{ runner.os }}-target-${{ github.sha }}
        fail-on-cache-miss: "true"
