runs:
  using: composite
  steps:
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        architecture: 'x64'
        distribution: 'zulu'

    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: "16.19.0"

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Configure sysctl limits for OpenSearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      shell: bash

    - name: Start Postgres and OS containers
      run: docker-compose up -d
      shell: bash
