@startuml

title OAuth2 -tietokanta KOSKI-backendissä
rectangle #White {

Note as taulu
 Toistaiseksi vain yksi taulu.
end note

entity "oauth2_jako" as auth {
  *code_sha256: text <<primary key>>

  *oppija_oid: text
  *client_id : text

  *scope : text
  *code_challenge : text
  *redirect_uri : text

  access_token_sha256 : text unique

  *code_voimassa_asti : timestamptz
  *voimassa_asti : timestamptz

  *luotu : timestamptz
  *muokattu : timestamptz

  mitatoity : boolean
  mitatoity_syy : text
}

}

@enduml
