name: "Build Koski app + tests"
inputs:
  commithash:
    required: true
    type: string
    description: "Commit hash to build"
runs:
  using: composite
  steps:
    - name: Lookup existing target dir cache
      id: lookup
      uses: actions/cache/restore@v4
      with:
        path: target/
        key: ${{ runner.os }}-target-${{ inputs.commithash }}
        lookup-only: "true"
    - uses: actions/checkout@v4
      if: steps.lookup.outputs.cache-hit != 'true'
      with:
        ref: ${{ inputs.commithash }}
    - uses: ./.github/actions/setup_pnpm_cache
    - name: Setup Node
      if: steps.lookup.outputs.cache-hit != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: "22.14.0"
    - if: steps.lookup.outputs.cache-hit != 'true'
      uses: ./.github/actions/setup_java_11
    - name: Build Koski app + tests
      if: steps.lookup.outputs.cache-hit != 'true'
      env:
        version: ${{ inputs.commithash }}
      run: |
        mvn versions:set -DnewVersion="$version" --batch-mode
        mvn test -DskipTests=true --batch-mode
      shell: bash
    - name: Cache target dir
      if: steps.lookup.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: target/
        key: ${{ runner.os }}-target-${{ inputs.commithash }}
