---

- name: Koski upload
  hosts: tor_backends:koski_backends
  sudo: true
  gather_facts: False
  tasks:
  - name: Copy koski application package
    copy: src={{ koski_package }} dest=/tmp/{{ koski_package | basename }}

- name: Koski deployment
  hosts: tor_backends:koski_backends
  sudo: true
  gather_facts: False
  vars:
    koski_home: /srv/tomcat/koski
    koski_user: tomcat
    koski_deploy_dir: "{{ koski_home }}/deploy"
  serial: 1
  tasks:
  - name: Stop koski service
    service: name=koski state=stopped
  - name: Remove old application directory
    file: path={{ koski_deploy_dir }} state=absent
  - name: Create application directory
    file: path={{ koski_deploy_dir }} state=directory
  - name: Unpack koski application package
    unarchive:
      copy=no
      src=/tmp/{{ koski_package | basename }}
      dest={{ koski_deploy_dir }}
      group={{ koski_user }}
      owner={{ koski_user }}
  - name: Start koski service
    service: name=koski state=started
  - name: Check for application responding
    shell: curl -f http://127.0.0.1:8080/koski/buildversion.txt >> /dev/null
    register: task_result
    until: task_result.rc == 0
    retries: 60
    delay: 1