---

- name: Koski deployment
  hosts: koski_backends:koski-validation_backends:koski-raportointikanta_backends
  become: true
  gather_facts: False
  vars:
    koski_home: /srv/tomcat/koski
    koski_user: tomcat
    koski_deploy_dir: "{{ koski_home }}/deploy"
  serial: 1
  tasks:
  - name: Read buildversion
    shell: unzip -q -c {{ koski_deploy_dir }}/koski-*.jar webapp/buildversion.txt
    register: buildversion
    ignore_errors: true
    args:
      warn: false
  - name: Previous version
    debug: var=buildversion.stdout_lines
    when: buildversion.failed is not defined or not buildversion.failed
  - name: Stop koski service
    service: name=koski state=stopped
  - name: Remove old application directory
    file: path={{ koski_deploy_dir }} state=absent
  - name: Create application directory
    file: path={{ koski_deploy_dir }} state=directory group={{ koski_user }} owner={{ koski_user }}
  - name: Upload koski application package
    copy:
      src={{ koski_package }}
      dest={{ koski_deploy_dir }}/{{ koski_package | basename }}
      group={{ koski_user }}
      owner={{ koski_user }}
  - name: Start koski service
    service: name=koski state=started
  - name: Check for application responding
    uri:
      url: http://127.0.0.1:8080/koski/buildversion.txt
      return_content: true
    register: task_result
    until: task_result['status']|default(0) == 200
    retries: 120
    delay: 1
  - name: New version
    debug: msg={{ task_result.content.split('\n') }}
    when: task_result.status == 200
