runs:
  using: composite
  steps:
    - name: Set GitHub Packages credentials for Maven
      shell: bash
      run: echo "KOSKI_GITHUB_PACKAGES_TOKEN=${{ github.token }}" >> $GITHUB_ENV
    - name: Set up Java 17 and 23
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
      with:
        java-version: |
          23
          17
        architecture: "x64"
        distribution: "zulu"
        cache: "maven"
