name: Valpas integration test

inputs:
  index:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Compile tests
      uses: nick-fields/retry@v2
      with:
        max_attempts: 1
        timeout_minutes: 20
        command: mvn test-compile --batch-mode

    - name: Run tests
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 45
        command: |
          cd valpas-web
          npm ci
          cd ..
          make valpas-fronttest-${{ inputs.index }}
