name: Valpas integration test

inputs:
  index:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup Java"
      uses: ./.github/actions/setup_java_11
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Run tests
      uses: nick-fields/retry@v3
      with:
        max_attempts: 2
        timeout_minutes: 45
        command: |
          cd valpas-web
          pnpm install --frozen-lockfile
          cd ..
          make valpas-fronttest-${{ inputs.index }}
