name: Valpas integration test

inputs:
  index:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "🔨 Setup Java"
      uses: ./.github/actions/setup_java_11
    - name: "🔨 Setup backend and databases"
      uses: ./.github/actions/setup_backend

    - name: Run tests
      uses: nick-fields/retry@v3
      env:
        PNPM_FROZEN_FLAG: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'snyk-io[bot]' && '--no-frozen-lockfile' || '--frozen-lockfile' }}
      with:
        max_attempts: 2
        timeout_minutes: 45
        command: |
          cd valpas-web
          pnpm install $PNPM_FROZEN_FLAG
          cd ..
          make valpas-fronttest-${{ inputs.index }}
