name: "👀"

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: "ubuntu-20.04"

env:
  DOCKER_BUILDKIT: 1
  TZ: Europe/Helsinki

jobs:
  lint_koski:
    name: Lint Koski
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          architecture: "x64"
          distribution: "zulu"

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run linter
        run: |
          cd web
          npm ci
          cd ..
          make lint

  checkdoc_koski_validation:
    name: validaation_muutoshistoria.md check
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Check validation and documentation changes
        run: |
          make checkdoc_validation

  checkdoc_koski_schema:
    name: tiedonsiirtoprotokollan_muutoshistoria.md check
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Check schema and documentation changes
        run: |
          make checkdoc_schema

  checkdoc_database_documentation:
    name: Database documentation check
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Check migration and database documentation changes
        run: |
          make checkdoc_dbdocs

  run_backend_tests_api_oppijavalidation:
    name: Backend (api oppijavalidation)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.api.oppijavalidation

  run_backend_tests_api_misc:
    name: Backend (api misc)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.api.misc, \
            fi.oph.koski.browserstack, \
            fi.oph.koski.cache

  run_backend_tests_nonmock:
    name: Backend (non-mock)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.nonmockloginsecurity

  run_backend_tests_other_1:
    name: Backend (other 1/3)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.browserstack, \
            fi.oph.koski.cache, \
            fi.oph.koski.editor, \
            fi.oph.koski.environment, \
            fi.oph.koski.etk, \
            fi.oph.koski.henkilo, \
            fi.oph.koski.http, \
            fi.oph.koski.integrationtest, \
            fi.oph.koski.json, \
            fi.oph.koski.kela, \
            fi.oph.koski.koodisto, \
            fi.oph.koski.koskiuser, \
            fi.oph.koski.localization, \
            fi.oph.koski.log, \
            fi.oph.koski.luovutuspalvelu, \
            fi.oph.koski.migration, \
            fi.oph.koski.migri, \
            fi.oph.koski.mocha, \
            fi.oph.koski.mydata, \
            fi.oph.koski.omaopintopolkuloki \
            fi.oph.koski.opiskeluoikeus, \
            fi.oph.koski.oppilaitos, \
            fi.oph.koski.organisaatio \
            fi.oph.koski.typemodel

  run_backend_tests_other_2:
    name: Backend (other 2/3)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.perftest, \
            fi.oph.koski.raportit, \
            fi.oph.koski.raportointikanta, \
            fi.oph.koski.schedule, \
            fi.oph.koski.schema, \
            fi.oph.koski.sso, \
            fi.oph.koski.sure, \
            fi.oph.koski.tools, \
            fi.oph.koski.userdirectory, \
            fi.oph.koski.util, \
            fi.oph.koski.valpas, \
            fi.oph.koski.versioning

  run_backend_tests_other_3:
    name: Backend (other 3/3)
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_backend_test
        with:
          suites: |
            fi.oph.koski.oppivelvollisuustieto, \
            fi.oph.koski.valvira, \
            fi.oph.koski.virta, \
            fi.oph.koski.ytl, \
            fi.oph.koski.ytr, \
            fi.oph.koski.ytl, \
            fi.oph.koski.meta, \
            fi.oph.koski.frontendvalvonta, \
            fi.oph.koski.tiedonsiirto \
            fi.oph.koski.suoritusjako \
            fi.oph.koski.suoritusjako.suoritetuttutkinnot

  run_frontend_tests:
    name: Frontend ${{matrix.shardIndex}}/${{matrix.shardTotal}}
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7]
        shardTotal: [7]
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_frontend_test
        with:
          shardIndex: ${{ matrix.shardIndex }}
          shardTotal: ${{ matrix.shardTotal }}

  run_frontend_playwright_tests:
    name: Playwright ${{matrix.shardIndex}}/${{matrix.shardTotal}}
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5]
        shardTotal: [5]
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/koski_frontend_playwright_test
        with:
          shardIndex: ${{ matrix.shardIndex }}
          shardTotal: ${{ matrix.shardTotal }}

  valpas_integration_tests:
    name: Valpas ${{matrix.shardIndex}}/${{matrix.shardTotal}}
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/valpas_integration_test
        with:
          index: ${{ matrix.shardIndex }}

  valpas_frontend_unit_tests:
    name: Valpas lint & unit
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run linter and tests
        run: |
          cd valpas-web
          npm ci
          npm run lint
          npm run test:unit
