name: Build
on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [master]
env:
  DOCKER_BUILDKIT: 1
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and upload artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH agent
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.ARTIFACTORY_DIST_KEY }}"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: "8"
          architecture: x64

      - name: Build and upload to Artifactory
        run: make dist version=$GITHUB_SHA
