name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/qa/prod)"
        required: true
        default: "dev"
      commithash:
        description: "Commit hash to deploy from"
        required: true
env:
  DOCKER_BUILDKIT: 1
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

run-name: Deploy to ${{ inputs.environment }}
jobs:
  build:
    name: Build Koski
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_koski
        with:
          commithash: ${{ inputs.commithash }}
  publish_image:
    name: Publish Koski Docker Image and package
    needs: [build]
    uses: ./.github/workflows/publish_image.yml
    with:
      commithash: ${{ inputs.commithash }}
    secrets: inherit
  deploy:
    name: Deploy
    needs: [publish_image]
    uses: ./.github/workflows/deploy_koski.yml
    with:
      environment: ${{ inputs.environment }}
      commithash: ${{ inputs.commithash }}
    secrets: inherit
