name: "👀OAuth2"

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: "ubuntu-latest"

env:
  DOCKER_BUILDKIT: 1
  TZ: Europe/Helsinki

jobs:
  test-client:
    name: OAuth2 client
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: "omadata-oauth2-sample/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "omadata-oauth2-sample/client/pnpm-lock.yaml"
      - run: cd omadata-oauth2-sample/client && pnpm install --frozen-lockfile
      - run: cd omadata-oauth2-sample/client && pnpm run lint
      - run: cd omadata-oauth2-sample/client && pnpm run build
        # TODO add test step when there are tests
  test-server:
    name: OAuth2 server
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: "omadata-oauth2-sample/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "omadata-oauth2-sample/server/pnpm-lock.yaml"
      - run: cd omadata-oauth2-sample/server && pnpm install --frozen-lockfile
      - run: cd omadata-oauth2-sample/server && pnpm run lint
      - run: cd omadata-oauth2-sample/server && pnpm run build
      # TODO add test step when there are tests
  test-e2e:
   name: OAuth2 E2E ${{matrix.shardIndex}}/${{matrix.shardTotal}}
   runs-on: ${{ inputs.runs-on }}
   permissions:
     contents: read
     id-token: write
   strategy:
     fail-fast: false
     matrix:
       shardIndex: [1]
       shardTotal: [1]
   if: ${{ !contains(github.event.head_commit.message, '[skip-tests]') }}
   steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Checkout luovutuspalvelu for e2e tests
       uses: actions/checkout@v4
       with:
         repository: Opetushallitus/koski-luovutuspalvelu
         path: koski-luovutuspalvelu

     - uses: ./.github/actions/omadataoauth2_e2e_test
       with:
         shardIndex: ${{ matrix.shardIndex }}
         shardTotal: ${{ matrix.shardTotal }}
         AWS_OPH_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
