name: Run smoketests
on:
  schedule:
    - cron: "30 5-12 * * MON-FRI"
  workflow_dispatch:

env:
  PNPM_FROZEN_FLAG: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'renovate[bot]' && '--no-frozen-lockfile' || '--frozen-lockfile' }}

jobs:
  smoketests:
    name:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"

      - uses: ./.github/actions/setup_pnpm_cache

      - name: Install dependencies
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          max_attempts: 5
          timeout_minutes: 5
          retry_wait_seconds: 120
          command: |
            cd smoketests
            pnpm install $PNPM_FROZEN_FLAG

      - name: Install Puppeteer browser
        run: |
          cd smoketests
          pnpm exec puppeteer browsers install chrome

      - name: Test kansalaisen näkymä testiopintopolussa
        run: cd smoketests && pnpm run qa:kansalainen

      - name: Test omadata-oauth2-sample testiopintopolussa
        run: cd smoketests && pnpm run omadata:qa

      - name: Report failure
        uses: ravsamhq/notify-slack-action@02b169fd81108a34dbb029df4a41dd27ad680290
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          notification_title: "Run smoketests: failure in kansalainen/omadata tests"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
