name: Trivy dependency check

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: "ubuntu-22.04"

permissions:
  contents: read

env:
  PNPM_FROZEN_FLAG: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'renovate[bot]' && '--no-frozen-lockfile' || '--frozen-lockfile' }}

jobs:
  trivy_dependency_check:
    name: Trivy dependency check
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./.github/actions/setup_pnpm_cache

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"

      - name: Install JS deps
        run: pnpm install --recursive $PNPM_FROZEN_FLAG

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 1
          scanners: vuln
          trivyignores: .trivyignore
          format: table
          severity: 'CRITICAL,HIGH'
          skip-dirs: 'src/main/resources/mockdata,src/test,target,omadata-oauth2-sample'
