name: Update Koski localizations
on: [workflow_dispatch]
  #schedule:
  #  - cron: "0 7 1 2-12/2 *"
jobs:
  updatelocalizations:
    name: Update localizations
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          architecture: 'x64'
          distribution: 'zulu'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d-%H%M%S')}" >> $GITHUB_STATE
      - name: Update localizations
        env:
          VIRKAILIJA_ROOT: https://virkailija.opintopolku.fi
        run: mvn exec:java -Dexec.mainClass="fi.oph.koski.localization.LocalizationMockDataUpdater"
      - name: Create PR with updated localizations
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
            commit-message: Päivitä Kosken lokalisaatiot
            title: "[${{ env.date }}]: Päivitä Kosken lokalisaatiot"
            body: |
              Tämä on automaattisesti luotu PR, jolla päivitetään Kosken käyttämät lokalisaatiot.

              Käy muutokset läpi ja korjaa mahdollisesti hajonneet testit.
            branch: tor-xxxx-koski-localization-update-${{ env.date }}
