name: Update Koski localizations
on: [workflow_dispatch]
  #schedule:
  #  - cron: "0 7 1 2-12/2 *"
jobs:
  updatelocalizations:
    name: Update localizations
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          architecture: 'x64'
          distribution: 'zulu'
          cache: 'maven'
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
          cache: 'npm'
          cache-dependency-path: |
            web/package-lock.json
            valpas-web/package-lock.json
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d-%H%M%S')}" >> $GITHUB_STATE
        shell: bash
      - name: Compile Koski & Valpas
        run: mvn -DskipTests=true clean install
        shell: bash
      - name: Update Koski localizations
        env:
          VIRKAILIJA_ROOT: https://virkailija.opintopolku.fi
          LOCALIZATION_CATEGORY: koski
        run: mvn exec:java -Dexec.mainClass=fi.oph.koski.localization.LocalizationMockDataUpdater
        shell: bash
      - name: Update Valpas localizations
        env:
          VIRKAILIJA_ROOT: https://virkailija.opintopolku.fi
          LOCALIZATION_CATEGORY: valpas
        run: mvn exec:java -Dexec.mainClass=fi.oph.koski.localization.LocalizationMockDataUpdater
        shell: bash
      - name: Create PR with updated localizations
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
            commit-message: Päivitä lokalisaatiot
            title: "[${{ env.date }}]: Päivitä lokalisaatiot"
            body: |
              Tämä on automaattisesti luotu PR, jolla päivitetään Koski- ja Valpas-palvelun käyttämät lokalisaatiot.

              Käy muutokset läpi ja korjaa mahdollisesti hajonneet testit.
            branch: tor-xxxx-koski-localization-update-${{ env.date }}
